title: Angela Di Serio 
logo: "images/Angela©k.c.61a Small.jpg" 
description: 
  Computer Engineer with a Master degree focused in Computer Science 
  and several relevant courses on Data Science and Big Data.
  Experienced Professor with a demonstrated history of working in the higher education. 
  Skilled in Programming Languages including C, Python, R, Java, Matlab; 
  Parallel Programming using MPI; Mobile Learning; Augmented Reality and Databases. 
  <br><br>
  
  <a href="https://www.linkedin.com/in/adiserio/">View My LinkedIn Profile</a> 
 
theme: jekyll-theme-architect
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
